version: "3.8"

services:
  backend:
    build: ./backend
    container_name: goport-backend
    ports:
      - "8095:8090"
    volumes:
      - goport_backend_data:/app/pb_data
    restart: unless-stopped

  landing:
    build: ./landing
    container_name: goport-landing
    ports:
      - "3005:3000"
    restart: unless-stopped

  server:
    build: ./server
    container_name: goport-server
    ports:
      - "8085:8080"
    restart: unless-stopped

volumes:
  goport_backend_data:
