from __future__ import annotations

import argparse
import math
import shutil
import subprocess
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from PIL import Image, ImageDraw, ImageFilter, ImageFont


ROOT = Path(__file__).resolve().parents[1]
GIF_DIR = ROOT / "gif"
LANDING_MEDIA = ROOT / "landing" / ".next" / "static" / "media"
CAPTURE_DIR = GIF_DIR / ".capture"
FRAMES_DIR = CAPTURE_DIR / "frames"

W = 1229
H = 417
PRIMARY = (47, 243, 146)
SKY = (0, 188, 254)
BG = (7, 11, 16)
CARD = (6, 6, 6, 77)
BORDER = (27, 27, 27, 155)
TEXT = (246, 246, 246, 255)
MUTED = (143, 143, 143, 255)
MUTED_DIM = (105, 105, 105, 255)
BASE_IMAGE: Image.Image | None = None


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate the GoPort tunnel diagram GIF.")
    parser.add_argument("--out", default=str(GIF_DIR / "goport-tunnel-linkedin.gif"))
    parser.add_argument("--fps", type=int, default=20)
    parser.add_argument("--duration", type=float, default=12.0)
    parser.add_argument("--base-time", type=float, default=10.36)
    parser.add_argument("--keep-frames", action="store_true")
    args = parser.parse_args()

    shutil.rmtree(CAPTURE_DIR, ignore_errors=True)
    FRAMES_DIR.mkdir(parents=True, exist_ok=True)

    fonts = load_fonts()
    frame_count = round(args.fps * args.duration)

    for i in range(frame_count):
        t = args.base_time + i / args.fps
        frame = render_frame(t, fonts)
        frame_path = FRAMES_DIR / f"frame_{i:04d}.png"
        frame.save(frame_path)
        if i % args.fps == 0:
            print(f"captured {i}/{frame_count}", end="\r", flush=True)
    print(f"captured {frame_count}/{frame_count}")

    out = Path(args.out).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    encode_gif(out, args.fps)

    if not args.keep_frames:
        shutil.rmtree(FRAMES_DIR, ignore_errors=True)
        (CAPTURE_DIR / "palette.png").unlink(missing_ok=True)

    print(f"wrote {out}")


def load_fonts() -> dict[str, ImageFont.FreeTypeFont]:
    # Latin subset generated by next/font for JetBrains Mono.
    source = LANDING_MEDIA / "70bc3e132a0a741e-s.p.1409xf.ylxg8g.woff2"
    if not source.exists():
        raise FileNotFoundError(f"JetBrains Mono subset not found: {source}")

    regular_ttf = CAPTURE_DIR / "jetbrains-mono-regular.ttf"
    medium_ttf = CAPTURE_DIR / "jetbrains-mono-medium.ttf"
    CAPTURE_DIR.mkdir(parents=True, exist_ok=True)

    regular_font = TTFont(source)
    regular_font.flavor = None
    regular_font.save(regular_ttf)

    medium_font = TTFont(source)
    if "fvar" in medium_font:
        medium_font = instancer.instantiateVariableFont(medium_font, {"wght": 600})
    medium_font.flavor = None
    medium_font.save(medium_ttf)

    return {
        "title": ImageFont.truetype(str(regular_ttf), 15),
        "label": ImageFont.truetype(str(medium_ttf), 15),
        "sub": ImageFont.truetype(str(regular_ttf), 13),
        "legend": ImageFont.truetype(str(regular_ttf), 14),
        "bottom": ImageFont.truetype(str(regular_ttf), 15),
    }


def render_frame(t: float, fonts: dict[str, ImageFont.FreeTypeFont]) -> Image.Image:
    global BASE_IMAGE
    scale = 2
    if BASE_IMAGE is None:
        BASE_IMAGE = Image.new("RGBA", (W * scale, H * scale), BG + (255,))
        draw_background(BASE_IMAGE, scale)
        draw_card(BASE_IMAGE, scale)
        draw_title(BASE_IMAGE, fonts, scale)
    img = BASE_IMAGE.copy()
    draw_diagram(img, fonts, t, scale)
    draw_legend(img, fonts, scale)
    draw_bottom_caption(img, fonts, scale)
    return img.resize((W, H), Image.Resampling.LANCZOS).convert("RGB")


def draw_background(img: Image.Image, scale: int) -> None:
    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    for x in range(22, W, 22):
        for y in range(22, H, 22):
            draw.ellipse(
                box((x - 1, y - 1, x + 1, y + 1), scale),
                fill=(148, 163, 184, 25),
            )

    glow = Image.new("RGBA", img.size, (0, 0, 0, 0))
    gd = ImageDraw.Draw(glow)
    gd.ellipse(box((235, -250, 995, 170), scale), fill=PRIMARY + (20,))
    glow = glow.filter(ImageFilter.GaussianBlur(130 * scale))
    img.alpha_composite(glow)

    vignette = Image.new("RGBA", img.size, (0, 0, 0, 0))
    pix = vignette.load()
    cx, cy = W * 0.5, H * 0.35
    rx, ry = W * 0.65, H * 0.50
    for yy in range(H):
        for xx in range(W):
            d = math.sqrt(((xx - cx) / rx) ** 2 + ((yy - cy) / ry) ** 2)
            if d > 0.55:
                a = min(210, int((d - 0.55) / 0.45 * 210))
                pix[xx * scale, yy * scale] = (7, 11, 16, a)
    vignette = vignette.resize(img.size, Image.Resampling.BILINEAR)
    img.alpha_composite(overlay)
    img.alpha_composite(vignette)


def draw_card(img: Image.Image, scale: int) -> None:
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    rounded(draw, (0, 0, W, H), 16, scale, fill=CARD, outline=BORDER, width=1)
    img.alpha_composite(layer)


def draw_title(img: Image.Image, fonts: dict[str, ImageFont.FreeTypeFont], scale: int) -> None:
    draw = ImageDraw.Draw(img)
    rect = (435, 41, 782, 72)
    rounded(draw, rect, 8, scale, fill=(1, 1, 1, 150), outline=BORDER, width=1)
    centered_text(draw, rect, "Fig. 1 \u2014 Anatomy of a secure tunnel", fonts["title"], MUTED, scale)


def draw_diagram(img: Image.Image, fonts: dict[str, ImageFont.FreeTypeFont], t: float, scale: int) -> None:
    connectors = [(186, 371), (498, 683), (846, 1031)]
    for index, (x1, x2) in enumerate(connectors):
        draw_connector(img, x1, x2, 188, 203, dashed=(index == 1), scale=scale)

    for x1, x2 in connectors:
        draw_packet(img, x1, x2, 188, t, PRIMARY, reverse=False, delay=0.0, scale=scale)
        draw_packet(img, x1, x2, 203, t, SKY, reverse=True, delay=1.2, scale=scale)

    nodes = [
        (73, 133, "globe", "HTTP request", "from the internet", "normal"),
        (395, 133, "cloud", "GoPort Cloud", "secure tunnel", "highlight"),
        (725, 133, "terminal", "GoPort CLI agent", "on your machine", "normal"),
        (1065, 133, "monitor", "localhost:8080", "your app", "accent"),
    ]

    draw_cloud_glow(img, (395, 133, 475, 213), t, scale)
    for x, y, icon, label, sublabel, variant in nodes:
        draw_node(img, x, y, icon, variant, scale)
        cx = x + 40
        centered_text_at(img, cx, 226, label, fonts["label"], TEXT, scale)
        centered_text_at(img, cx, 248, sublabel, fonts["sub"], MUTED, scale)


def draw_connector(img: Image.Image, x1: int, x2: int, y_top: int, y_bottom: int, dashed: bool, scale: int) -> None:
    draw = ImageDraw.Draw(img, "RGBA")
    if dashed:
        for y, color, alpha in ((y_top, PRIMARY, 105), (y_bottom, SKY, 78)):
            x = x1
            while x < x2:
                draw.line((x * scale, y * scale, min(x + 6, x2) * scale, y * scale), fill=color + (alpha,), width=max(1, scale))
                x += 14
    else:
        gradient_line(draw, x1, x2, y_top, PRIMARY, 50, 125, scale)
        gradient_line(draw, x1, x2, y_bottom, SKY, 50, 100, scale)


def gradient_line(draw: ImageDraw.ImageDraw, x1: int, x2: int, y: int, color: tuple[int, int, int], a1: int, a2: int, scale: int) -> None:
    for x in range(x1, x2):
        p = (x - x1) / max(1, x2 - x1)
        center = 1 - abs(p - 0.5) * 2
        alpha = int(a1 + (a2 - a1) * center)
        draw.line((x * scale, y * scale, (x + 1) * scale, y * scale), fill=color + (alpha,), width=max(1, scale))


def draw_packet(
    img: Image.Image,
    x1: int,
    x2: int,
    y: int,
    t: float,
    color: tuple[int, int, int],
    reverse: bool,
    delay: float,
    scale: int,
) -> None:
    duration = 2.4
    progress = ((t - delay) % duration) / duration
    opacity = packet_opacity(progress)
    width = x2 - x1
    size = 10
    if reverse:
        cx = x2 - progress * width - size / 2
    else:
        cx = x1 + progress * width + size / 2
    draw_glow_dot(img, cx, y, size / 2, color, int(255 * opacity), scale)


def packet_opacity(progress: float) -> float:
    if progress < 0.10:
        return progress / 0.10
    if progress > 0.90:
        return max(0.0, (1 - progress) / 0.10)
    return 1.0


def draw_cloud_glow(img: Image.Image, rect: tuple[int, int, int, int], t: float, scale: int) -> None:
    phase = (t % 3.0) / 3.0
    pulse = 0.5 - 0.5 * math.cos(2 * math.pi * phase)
    blur = (23 + 18 * pulse) * scale
    alpha = int(38 + 34 * pulse)
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(layer)
    grow = 22 + 10 * pulse
    x1, y1, x2, y2 = rect
    rounded(draw, (x1 - grow, y1 - grow, x2 + grow, y2 + grow), 24, scale, fill=PRIMARY + (alpha,), outline=None)
    layer = layer.filter(ImageFilter.GaussianBlur(blur))
    img.alpha_composite(layer)


def draw_node(img: Image.Image, x: int, y: int, icon: str, variant: str, scale: int) -> None:
    draw = ImageDraw.Draw(img, "RGBA")
    if variant == "highlight":
        outline = PRIMARY + (120,)
        icon_color = PRIMARY + (255,)
    elif variant == "accent":
        outline = PRIMARY + (95,)
        icon_color = PRIMARY + (255,)
    else:
        outline = (70, 70, 70, 180)
        icon_color = (255, 255, 255, 255)

    rounded(draw, (x, y, x + 80, y + 80), 18, scale, fill=(1, 1, 1, 218), outline=outline, width=1)
    cx, cy = x + 40, y + 40
    if icon == "globe":
        icon_globe(draw, cx, cy, icon_color, scale)
    elif icon == "cloud":
        icon_cloud(draw, cx, cy, icon_color, scale)
    elif icon == "terminal":
        icon_terminal(draw, cx, cy, icon_color, scale)
    elif icon == "monitor":
        icon_monitor(draw, cx, cy, icon_color, scale)


def draw_legend(img: Image.Image, fonts: dict[str, ImageFont.FreeTypeFont], scale: int) -> None:
    draw_glow_dot(img, 517, 304, 5, PRIMARY, 255, scale, shadow=False)
    draw_glow_dot(img, 624, 304, 5, SKY, 255, scale, shadow=False)
    draw = ImageDraw.Draw(img)
    text(draw, (532, 297), "request", fonts["legend"], MUTED, scale)
    text(draw, (639, 297), "response", fonts["legend"], MUTED, scale)


def draw_bottom_caption(img: Image.Image, fonts: dict[str, ImageFont.FreeTypeFont], scale: int) -> None:
    draw = ImageDraw.Draw(img)
    centered_text_at(
        img,
        W // 2,
        370,
        "Your machine becomes a server \u2014 instantly, no port forwarding required.",
        fonts["bottom"],
        MUTED_DIM,
        scale,
    )


def draw_glow_dot(
    img: Image.Image,
    cx: float,
    cy: float,
    radius: float,
    color: tuple[int, int, int],
    alpha: int,
    scale: int,
    shadow: bool = True,
) -> None:
    if alpha <= 0:
        return
    if shadow:
        layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
        draw = ImageDraw.Draw(layer)
        draw.ellipse(box((cx - radius * 2.4, cy - radius * 2.4, cx + radius * 2.4, cy + radius * 2.4), scale), fill=color + (int(alpha * 0.55),))
        layer = layer.filter(ImageFilter.GaussianBlur(5 * scale))
        img.alpha_composite(layer)
    draw = ImageDraw.Draw(img, "RGBA")
    draw.ellipse(box((cx - radius, cy - radius, cx + radius, cy + radius), scale), fill=color + (alpha,))


def icon_globe(draw: ImageDraw.ImageDraw, cx: int, cy: int, color: tuple[int, int, int, int], scale: int) -> None:
    sw = 4 * scale
    draw.ellipse(box((cx - 16, cy - 16, cx + 16, cy + 16), scale), outline=color, width=sw)
    draw.arc(box((cx - 8, cy - 16, cx + 8, cy + 16), scale), 90, 270, fill=color, width=sw)
    draw.arc(box((cx - 8, cy - 16, cx + 8, cy + 16), scale), 270, 90, fill=color, width=sw)
    draw.line(((cx - 16) * scale, cy * scale, (cx + 16) * scale, cy * scale), fill=color, width=sw)


def icon_cloud(draw: ImageDraw.ImageDraw, cx: int, cy: int, color: tuple[int, int, int, int], scale: int) -> None:
    pts = []
    pts += bezier((cx - 15, cy + 8), (cx - 22, cy + 8), (cx - 23, cy - 6), (cx - 10, cy - 6), 14)
    pts += bezier((cx - 10, cy - 6), (cx - 7, cy - 17), (cx + 8, cy - 13), (cx + 9, cy - 4), 14)
    pts += bezier((cx + 9, cy - 4), (cx + 20, cy - 5), (cx + 24, cy + 8), (cx + 12, cy + 8), 14)
    pts.append((cx - 15, cy + 8))
    pts = [(x * scale, y * scale) for x, y in pts]
    draw.line(pts, fill=color, width=4 * scale, joint="curve")


def icon_terminal(draw: ImageDraw.ImageDraw, cx: int, cy: int, color: tuple[int, int, int, int], scale: int) -> None:
    sw = 4 * scale
    draw.line(((cx - 13) * scale, (cy - 12) * scale, (cx - 2) * scale, cy * scale, (cx - 13) * scale, (cy + 12) * scale), fill=color, width=sw, joint="curve")
    draw.line(((cx + 3) * scale, (cy + 13) * scale, (cx + 15) * scale, (cy + 13) * scale), fill=color, width=sw)


def icon_monitor(draw: ImageDraw.ImageDraw, cx: int, cy: int, color: tuple[int, int, int, int], scale: int) -> None:
    sw = 4 * scale
    rounded(draw, (cx - 18, cy - 13, cx + 7, cy + 6), 3, scale, fill=None, outline=color, width=4)
    draw.line(((cx - 6) * scale, (cy + 9) * scale, (cx - 6) * scale, (cy + 16) * scale), fill=color, width=sw)
    draw.line(((cx - 13) * scale, (cy + 17) * scale, (cx - 1) * scale, (cy + 17) * scale), fill=color, width=sw)
    rounded(draw, (cx + 6, cy + 1, cx + 19, cy + 22), 4, scale, fill=None, outline=color, width=4)


def bezier(p0: tuple[float, float], p1: tuple[float, float], p2: tuple[float, float], p3: tuple[float, float], steps: int) -> list[tuple[float, float]]:
    pts = []
    for i in range(steps + 1):
        t = i / steps
        u = 1 - t
        x = u**3 * p0[0] + 3 * u * u * t * p1[0] + 3 * u * t * t * p2[0] + t**3 * p3[0]
        y = u**3 * p0[1] + 3 * u * u * t * p1[1] + 3 * u * t * t * p2[1] + t**3 * p3[1]
        pts.append((x, y))
    return pts


def rounded(
    draw: ImageDraw.ImageDraw,
    rect: tuple[float, float, float, float],
    radius: float,
    scale: int,
    fill: tuple[int, int, int, int] | None,
    outline: tuple[int, int, int, int] | None,
    width: int = 1,
) -> None:
    draw.rounded_rectangle(box(rect, scale), radius=radius * scale, fill=fill, outline=outline, width=width * scale)


def box(rect: tuple[float, float, float, float], scale: int) -> tuple[int, int, int, int]:
    return tuple(round(v * scale) for v in rect)  # type: ignore[return-value]


def text(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    value: str,
    font: ImageFont.FreeTypeFont,
    fill: tuple[int, int, int, int],
    scale: int,
) -> None:
    draw.text((xy[0] * scale, xy[1] * scale), value, font=font_variant(font, scale), fill=fill)


def centered_text(
    draw: ImageDraw.ImageDraw,
    rect: tuple[int, int, int, int],
    value: str,
    font: ImageFont.FreeTypeFont,
    fill: tuple[int, int, int, int],
    scale: int,
) -> None:
    f = font_variant(font, scale)
    bbox = draw.textbbox((0, 0), value, font=f)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    x = (rect[0] + rect[2]) * scale / 2 - tw / 2
    y = (rect[1] + rect[3]) * scale / 2 - th / 2 - 1 * scale
    draw.text((x, y), value, font=f, fill=fill)


def centered_text_at(
    img: Image.Image,
    cx: int,
    y: int,
    value: str,
    font: ImageFont.FreeTypeFont,
    fill: tuple[int, int, int, int],
    scale: int,
) -> None:
    draw = ImageDraw.Draw(img)
    f = font_variant(font, scale)
    bbox = draw.textbbox((0, 0), value, font=f)
    tw = bbox[2] - bbox[0]
    draw.text((cx * scale - tw / 2, y * scale), value, font=f, fill=fill)


def font_variant(font: ImageFont.FreeTypeFont, scale: int) -> ImageFont.FreeTypeFont:
    return font.font_variant(size=font.size * scale)


def encode_gif(out: Path, fps: int) -> None:
    palette = CAPTURE_DIR / "palette.png"
    run(
        [
            "ffmpeg",
            "-y",
            "-framerate",
            str(fps),
            "-i",
            str(FRAMES_DIR / "frame_%04d.png"),
            "-vf",
            "palettegen=stats_mode=diff",
            str(palette),
        ]
    )
    run(
        [
            "ffmpeg",
            "-y",
            "-framerate",
            str(fps),
            "-i",
            str(FRAMES_DIR / "frame_%04d.png"),
            "-i",
            str(palette),
            "-lavfi",
            "paletteuse=dither=bayer:bayer_scale=3",
            "-loop",
            "0",
            str(out),
        ]
    )


def run(cmd: list[str]) -> None:
    completed = subprocess.run(cmd, check=False, capture_output=True, text=True)
    if completed.returncode != 0:
        if completed.stdout:
            print(completed.stdout)
        if completed.stderr:
            print(completed.stderr)
        raise RuntimeError(f"{cmd[0]} failed with exit code {completed.returncode}")


if __name__ == "__main__":
    main()
